Repository vegaprotocol/protos, pull requests merged in 2022-05, with the labels that each got.

#422 Update oracle data documentation
  generated/json/data-node/api/v1/ObserveEventBusResponse.json
  generated/json/data-node/api/v1/OracleDataBySpecResponse.json
  generated/proto.json
  sources/vega/oracles/v1/data.proto
  swagger/data-node/api/v1/trading_data.swagger.json
  swagger/vega/api/v1/core.swagger.json
  vega/oracles/v1/data.pb.go
Labels: oracles, no-changelog

#429 fix: validation of transfer dispatch metric
  commands/transfer_funds.go
Labels: no-changelog

#430 chore: added optional empty orders for party and snapshot for state v…
  generated/proto.json
  sources/vega/snapshot/v1/snapshot.proto
  vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#431 chore: added to state var snapshot
  generated/proto.json
  sources/vega/snapshot/v1/snapshot.proto
  vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#434 chore: also regenerate files
  generated/json/data-node/api/v1/ObserveEventBusResponse.json
  generated/proto.json
  swagger/data-node/api/v1/trading_data.swagger.json
  swagger/vega/api/v1/core.swagger.json
  swagger/vega/api/v1/corestate.swagger.json
  vega/events/v1/events.pb.go
Labels: no-changelog

#439 chore: add extension_event_sent to auctionState snapshot
  generated/proto.json
  sources/vega/snapshot/v1/snapshot.proto
  vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#441 feat: add previous_sequence_number to MarketDataUpdate
  CHANGELOG.md
  generated/json/data-node/api/v1/MarketDepthUpdatesSubscribeResponse.json
  generated/json/vega/MarketDepthUpdate.json
  generated/proto.json
  sources/vega/vega.proto
  swagger/data-node/api/v1/trading_data.swagger.json
  vega/vega.pb.go
Labels: 🧮 DatanodeV2

#443 fix: Check for asset ID on update asset proposal
  commands/proposal_submission.go
  commands/proposal_submission_update_asset_test.go
Labels: no-changelog

#447 Add ERC20AssetLimitsUpdated chain event
  generated/json/vega/ERC20AssetLimitsUpdated.json
  generated/json/vega/ERC20Event.json
  generated/proto.json
  sources/vega/chain_events.proto
  vega/chain_events.pb.go
Labels: no-changelog
